# Generated by Django 2.1.4 on 2018-12-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_login_date',
            field=models.DateTimeField(blank=True, max_length=32, null=True, verbose_name='上一次登录时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='login_lock_date',
            field=models.DateTimeField(blank=True, max_length=32, null=True, verbose_name='登录锁定时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='座机'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='session',
            field=models.CharField(blank=True, default='None', max_length=32, null=True),
        ),
    ]
