# Generated by Django 2.1.4 on 2018-12-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20181221_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='login_lock_date',
            field=models.DateTimeField(blank=True, default='1970-01-01 00:00:00', max_length=32, null=True, verbose_name='登录锁定时间'),
        ),
    ]
