# Generated by Django 2.1.3 on 2018-12-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20181205_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='login_lock_date',
            field=models.DateField(null=True, verbose_name='登录锁定时间'),
        ),
    ]
