# Generated by Django 2.1.3 on 2018-12-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20181205_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='login_lock_date',
            field=models.DateField(max_length=32, null=True, verbose_name='登录锁定时间'),
        ),
    ]
