# Generated by Django 2.1.3 on 2018-12-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20181205_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login_date',
            field=models.DateTimeField(max_length=32, null=True, verbose_name='上一次登录时间'),
        ),
    ]
