# Generated by Django 2.1.3 on 2018-12-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_userprofile_last_login_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='session',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
