# Generated by Django 2.1.3 on 2018-12-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='level',
            field=models.IntegerField(default=1, max_length=32, verbose_name='菜单级别'),
            preserve_default=False,
        ),
    ]
