# Generated by Django 2.1.3 on 2018-12-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_menu_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='level',
            field=models.IntegerField(verbose_name='菜单级别'),
        ),
    ]
