# Generated by Django 2.1.3 on 2018-12-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20181210_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='note',
            field=models.CharField(default=1, max_length=32, verbose_name='注释'),
            preserve_default=False,
        ),
    ]
