# Generated by Django 2.1.3 on 2018-12-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_role_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='note',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='注释'),
        ),
    ]
