# Generated by Django 2.1.3 on 2018-12-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20181205_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='login_suo',
            field=models.DateTimeField(default=0, verbose_name='登录锁定时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pass_errnum',
            field=models.IntegerField(default=0, verbose_name='用户密码输入次数'),
        ),
    ]
