# Generated by Django 2.1.3 on 2018-12-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20181205_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_suo',
        ),
    ]
