# Generated by Django 2.1.3 on 2018-12-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_remove_user_login_suo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_login',
        ),
    ]
