# Generated by Django 2.1.3 on 2018-12-05 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_user_login_suo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pass_errnum',
            new_name='pass_errn',
        ),
    ]
