# Generated by Django 2.1.3 on 2018-12-07 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0010_auto_20181205_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission2action2role',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2as', to='rbac.Role', verbose_name='角色'),
        ),
    ]
