# Generated by Django 2.1.3 on 2018-12-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0011_auto_20181207_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission2action2role',
            name='role',
        ),
        migrations.AlterUniqueTogether(
            name='permission2action2role',
            unique_together={('permission', 'action')},
        ),
    ]
