# Generated by Django 2.1.3 on 2018-12-07 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0012_auto_20181207_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissionAction', models.ManyToManyField(to='rbac.Permission2Action2Role', verbose_name='权限及方法')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2as', to='rbac.Role', verbose_name='角色')),
            ],
        ),
    ]
