# Generated by Django 2.1.3 on 2018-12-07 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0013_permissionrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionrole',
            name='permissionAction',
        ),
        migrations.RemoveField(
            model_name='permissionrole',
            name='role',
        ),
        migrations.AddField(
            model_name='permission2action2role',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2as', to='rbac.Role', verbose_name='角色'),
        ),
        migrations.AlterUniqueTogether(
            name='permission2action2role',
            unique_together={('permission', 'action', 'role')},
        ),
        migrations.DeleteModel(
            name='PermissionRole',
        ),
    ]
